// <auto-generated />
namespace TravelTrip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class db_comments_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_comments_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202305031733415_db_comments_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
